// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for aboutUs documents */
type AboutusDocumentData = Record<string, never>;
/**
 * aboutUs document from Prismic
 *
 * - **API ID**: `aboutus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutusDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<AboutusDocumentData>, "aboutus", Lang>;
/** Content for Company info documents */
interface CompanyInfoDocumentData {
    /**
     * title field in *Company info*
     *
     * - **Field Type**: Title
     * - **Placeholder**: title of component
     * - **API ID Path**: company_info.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * paragraph field in *Company info*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: component paragraph
     * - **API ID Path**: company_info.paragraph
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
    /**
     * image field in *Company info*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * read more link field in *Company info*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.read_more_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    read_more_link: prismicT.LinkField;
    /**
     * read more text field in *Company info*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.read_more_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    read_more_text: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Company info*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<CompanyInfoDocumentDataSlicesSlice>;
}
/**
 * Slice for *Company info → Slice Zone*
 *
 */
type CompanyInfoDocumentDataSlicesSlice = never;
/**
 * Company info document from Prismic
 *
 * - **API ID**: `company_info`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompanyInfoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CompanyInfoDocumentData>, "company_info", Lang>;
/** Content for Contact Elements documents */
interface ContactElementsDocumentData {
    /**
     * phone paragraph field in *Contact Elements*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.phone_paragraph
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    phone_paragraph: prismicT.RichTextField;
    /**
     * phone link field in *Contact Elements*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.phone_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    phone_link: prismicT.LinkToMediaField;
    /**
     * phone number field in *Contact Elements*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.phone_number
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone_number: prismicT.KeyTextField;
    /**
     * mail paragraph field in *Contact Elements*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.mail_paragraph
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    mail_paragraph: prismicT.RichTextField;
    /**
     * mail link field in *Contact Elements*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.mail_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    mail_link: prismicT.LinkField;
    /**
     * mail address field in *Contact Elements*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.mail_address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    mail_address: prismicT.KeyTextField;
    /**
     * location paragraph field in *Contact Elements*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.location_paragraph
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    location_paragraph: prismicT.RichTextField;
    /**
     * location link field in *Contact Elements*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.location_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    location_link: prismicT.LinkToMediaField;
    /**
     * location field in *Contact Elements*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.location
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    location: prismicT.KeyTextField;
}
/**
 * Contact Elements document from Prismic
 *
 * - **API ID**: `contact_elements`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactElementsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ContactElementsDocumentData>, "contact_elements", Lang>;
/** Content for Dentists documents */
interface DentistsDocumentData {
    /**
     * Slice Zone field in *Dentists*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: dentists.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<DentistsDocumentDataSlicesSlice>;
}
/**
 * Slice for *Dentists → Slice Zone*
 *
 */
type DentistsDocumentDataSlicesSlice = DentistSlice;
/**
 * Dentists document from Prismic
 *
 * - **API ID**: `dentists`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DentistsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<DentistsDocumentData>, "dentists", Lang>;
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * company name field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.company_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_name: prismicT.RichTextField;
    /**
     * licence number field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.licence_number
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    licence_number: prismicT.RichTextField;
    /**
     * company address field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.company_address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_address: prismicT.RichTextField;
    /**
     * company phone field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.company_phone
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_phone: prismicT.RichTextField;
    /**
     * company mail field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.company_mail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_mail: prismicT.RichTextField;
}
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Hero documents */
interface HomepageDocumentData {
    /**
     * title field in *Hero*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * company slogan field in *Hero*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.company_slogan
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_slogan: prismicT.TitleField;
    /**
     * cover photo mobile field in *Hero*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.cover_photo_mobile
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_photo_mobile: prismicT.ImageField<never>;
    /**
     * cover photo tablet field in *Hero*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.cover_photo_tablet
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_photo_tablet: prismicT.ImageField<never>;
    /**
     * cover photo desktop field in *Hero*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.cover_photo_desktop
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_photo_desktop: prismicT.ImageField<never>;
    /**
     * about company link field in *Hero*
     *
     * - **Field Type**: Link
     * - **Placeholder**: link to about page
     * - **API ID Path**: homepage.about_company_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    about_company_link: prismicT.LinkField;
    /**
     * about link text field in *Hero*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.about_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_link_text: prismicT.KeyTextField;
    /**
     * book appointment link field in *Hero*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.book_appointment_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    book_appointment_link: prismicT.LinkField;
    /**
     * book appointment text field in *Hero*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.book_appointment_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    book_appointment_text: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Hero*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Hero → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = LandingPageSlice | CompanyInfoSlice;
/**
 * Hero document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
    /**
     * logo field in *Navigation*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * logo text field in *Navigation*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.logo_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    logo_text: prismicT.TitleField;
    /**
     * logo subtext field in *Navigation*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.logo_subtext
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    logo_subtext: prismicT.RichTextField;
    /**
     * Home Link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.home_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    home_link: prismicT.LinkField;
    /**
     * Home Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.home_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    home_link_text: prismicT.KeyTextField;
    /**
     * About Link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.about_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    about_link: prismicT.LinkField;
    /**
     * About Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.about_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_link_text: prismicT.KeyTextField;
    /**
     * Service link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.service_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    service_link: prismicT.LinkField;
    /**
     * service text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.service_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    service_text: prismicT.KeyTextField;
    /**
     * Specialists Link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.specialists_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    specialists_link: prismicT.LinkField;
    /**
     * Specialists Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.specialists_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    specialists_link_text: prismicT.KeyTextField;
    /**
     * Contact link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.contact_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    contact_link: prismicT.LinkField;
    /**
     * Contact Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.contact_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    contact_link_text: prismicT.KeyTextField;
    /**
     * phone link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.phone_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    phone_link: prismicT.LinkField;
    /**
     * phone number text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.phone_number_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone_number_text: prismicT.KeyTextField;
    /**
     * book appointment link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.book_appointment_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    book_appointment_link: prismicT.LinkField;
    /**
     * book appointment text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.book_appointment_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    book_appointment_text: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice = never;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;
export type AllDocumentTypes = AboutusDocument | CompanyInfoDocument | ContactElementsDocument | DentistsDocument | FooterDocument | HomepageDocument | NavigationDocument;
/**
 * Primary content in CompanyInfo → Primary
 *
 */
interface CompanyInfoSliceDefaultPrimary {
    /**
     * Title field in *CompanyInfo → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: company_info.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *CompanyInfo → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: company_info.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * read more field in *CompanyInfo → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.primary.read_more
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    read_more: prismicT.LinkField;
    /**
     * read more text field in *CompanyInfo → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.primary.read_more_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    read_more_text: prismicT.KeyTextField;
    /**
     * image field in *CompanyInfo → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for CompanyInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CompanyInfo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CompanyInfoSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CompanyInfoSliceDefaultPrimary>, never>;
/**
 * Slice variation for *CompanyInfo*
 *
 */
type CompanyInfoSliceVariation = CompanyInfoSliceDefault;
/**
 * CompanyInfo Shared Slice
 *
 * - **API ID**: `company_info`
 * - **Description**: `CompanyInfo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CompanyInfoSlice = prismicT.SharedSlice<"company_info", CompanyInfoSliceVariation>;
/**
 * Primary content in Dentist → Primary
 *
 */
interface DentistSliceDefaultPrimary {
    /**
     * name field in *Dentist → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: dentist.primary.name
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
    /**
     * education field in *Dentist → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: dentist.primary.education
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    education: prismicT.TitleField;
    /**
     * profile image field in *Dentist → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: dentist.primary.profile_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    profile_image: prismicT.ImageField<never>;
}
/**
 * Default variation for Dentist Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Dentist`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DentistSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<DentistSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Dentist*
 *
 */
type DentistSliceVariation = DentistSliceDefault;
/**
 * Dentist Shared Slice
 *
 * - **API ID**: `dentist`
 * - **Description**: `Dentist`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DentistSlice = prismicT.SharedSlice<"dentist", DentistSliceVariation>;
/**
 * Primary content in LandingPage → Primary
 *
 */
interface LandingPageSliceDefaultPrimary {
    /**
     * Description field in *LandingPage → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: landing_page.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * more link field in *LandingPage → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.more_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    more_link: prismicT.LinkField;
    /**
     * more text field in *LandingPage → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.more_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    more_text: prismicT.KeyTextField;
    /**
     * book appointment link field in *LandingPage → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.book_appointment_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    book_appointment_link: prismicT.LinkField;
    /**
     * book appointment text field in *LandingPage → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.book_appointment_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    book_appointment_text: prismicT.KeyTextField;
    /**
     * background image desktop field in *LandingPage → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.background_image_desktop
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image_desktop: prismicT.ImageField<never>;
    /**
     * background image tablet field in *LandingPage → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.background_image_tablet
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image_tablet: prismicT.ImageField<never>;
    /**
     * background image mobile field in *LandingPage → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.background_image_mobile
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image_mobile: prismicT.ImageField<never>;
    /**
     * welcome text field in *LandingPage → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.welcome_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    welcome_text: prismicT.RichTextField;
}
/**
 * Default variation for LandingPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: `LandingPage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LandingPageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<LandingPageSliceDefaultPrimary>, never>;
/**
 * Slice variation for *LandingPage*
 *
 */
type LandingPageSliceVariation = LandingPageSliceDefault;
/**
 * LandingPage Shared Slice
 *
 * - **API ID**: `landing_page`
 * - **Description**: `LandingPage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LandingPageSlice = prismicT.SharedSlice<"landing_page", LandingPageSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AboutusDocumentData, AboutusDocument, CompanyInfoDocumentData, CompanyInfoDocumentDataSlicesSlice, CompanyInfoDocument, ContactElementsDocumentData, ContactElementsDocument, DentistsDocumentData, DentistsDocumentDataSlicesSlice, DentistsDocument, FooterDocumentData, FooterDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, NavigationDocumentData, NavigationDocumentDataSlicesSlice, NavigationDocument, AllDocumentTypes, CompanyInfoSliceDefaultPrimary, CompanyInfoSliceDefault, CompanyInfoSliceVariation, CompanyInfoSlice, DentistSliceDefaultPrimary, DentistSliceDefault, DentistSliceVariation, DentistSlice, LandingPageSliceDefaultPrimary, LandingPageSliceDefault, LandingPageSliceVariation, LandingPageSlice };
    }
}
