// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for book appointment documents */
interface BookAppointmentDocumentData {
    /**
     * title field in *book appointment*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: book_appointment.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice Zone field in *book appointment*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: book_appointment.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<BookAppointmentDocumentDataSlicesSlice>;
}
/**
 * Slice for *book appointment → Slice Zone*
 *
 */
type BookAppointmentDocumentDataSlicesSlice = InputsSlice | TextSlice | TextWithTitleSlice;
/**
 * book appointment document from Prismic
 *
 * - **API ID**: `book_appointment`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BookAppointmentDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BookAppointmentDocumentData>, "book_appointment", Lang>;
/** Content for Company Info documents */
interface CompanyInfoDocumentData {
    /**
     * title field in *Company Info*
     *
     * - **Field Type**: Title
     * - **Placeholder**: title of component
     * - **API ID Path**: company_info.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * paragraph field in *Company Info*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: component paragraph
     * - **API ID Path**: company_info.paragraph
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
    /**
     * image field in *Company Info*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * read more link field in *Company Info*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.read_more_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    read_more_link: prismicT.LinkField;
    /**
     * read more text field in *Company Info*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.read_more_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    read_more_text: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Company Info*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<CompanyInfoDocumentDataSlicesSlice>;
}
/**
 * Slice for *Company Info → Slice Zone*
 *
 */
type CompanyInfoDocumentDataSlicesSlice = TextWithSlidingImagesSlice;
/**
 * Company Info document from Prismic
 *
 * - **API ID**: `company_info`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompanyInfoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CompanyInfoDocumentData>, "company_info", Lang>;
/** Content for Contact Elements documents */
interface ContactElementsDocumentData {
    /**
     * phone paragraph field in *Contact Elements*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.phone_paragraph
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    phone_paragraph: prismicT.RichTextField;
    /**
     * phone link field in *Contact Elements*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.phone_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    phone_link: prismicT.LinkToMediaField;
    /**
     * phone number field in *Contact Elements*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.phone_number
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone_number: prismicT.KeyTextField;
    /**
     * mail paragraph field in *Contact Elements*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.mail_paragraph
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    mail_paragraph: prismicT.RichTextField;
    /**
     * mail link field in *Contact Elements*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.mail_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    mail_link: prismicT.LinkField;
    /**
     * mail address field in *Contact Elements*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.mail_address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    mail_address: prismicT.KeyTextField;
    /**
     * location paragraph field in *Contact Elements*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.location_paragraph
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    location_paragraph: prismicT.RichTextField;
    /**
     * location link field in *Contact Elements*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.location_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    location_link: prismicT.LinkToMediaField;
    /**
     * location field in *Contact Elements*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_elements.location
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    location: prismicT.KeyTextField;
}
/**
 * Contact Elements document from Prismic
 *
 * - **API ID**: `contact_elements`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactElementsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ContactElementsDocumentData>, "contact_elements", Lang>;
/** Content for Dentists documents */
interface DentistsDocumentData {
    /**
     * Slice Zone field in *Dentists*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: dentists.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<DentistsDocumentDataSlicesSlice>;
}
/**
 * Slice for *Dentists → Slice Zone*
 *
 */
type DentistsDocumentDataSlicesSlice = DentistSlice;
/**
 * Dentists document from Prismic
 *
 * - **API ID**: `dentists`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DentistsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<DentistsDocumentData>, "dentists", Lang>;
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * company name field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.company_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_name: prismicT.RichTextField;
    /**
     * licence number field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.licence_number
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    licence_number: prismicT.RichTextField;
    /**
     * company address field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.company_address
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_address: prismicT.RichTextField;
    /**
     * company phone field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.company_phone
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_phone: prismicT.RichTextField;
    /**
     * company mail field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.company_mail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_mail: prismicT.RichTextField;
}
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Hero documents */
interface HomepageDocumentData {
    /**
     * title field in *Hero*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * company slogan field in *Hero*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.company_slogan
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_slogan: prismicT.TitleField;
    /**
     * cover photo mobile field in *Hero*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.cover_photo_mobile
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_photo_mobile: prismicT.ImageField<never>;
    /**
     * cover photo tablet field in *Hero*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.cover_photo_tablet
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_photo_tablet: prismicT.ImageField<never>;
    /**
     * cover photo desktop field in *Hero*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.cover_photo_desktop
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_photo_desktop: prismicT.ImageField<never>;
    /**
     * about company link field in *Hero*
     *
     * - **Field Type**: Link
     * - **Placeholder**: link to about page
     * - **API ID Path**: homepage.about_company_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    about_company_link: prismicT.LinkField;
    /**
     * about link text field in *Hero*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.about_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_link_text: prismicT.KeyTextField;
    /**
     * book appointment link field in *Hero*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.book_appointment_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    book_appointment_link: prismicT.LinkField;
    /**
     * book appointment text field in *Hero*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.book_appointment_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    book_appointment_text: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Hero*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Hero → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = never;
/**
 * Hero document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
    /**
     * logo field in *Navigation*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * logo text field in *Navigation*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.logo_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    logo_text: prismicT.TitleField;
    /**
     * logo subtext field in *Navigation*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.logo_subtext
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    logo_subtext: prismicT.RichTextField;
    /**
     * Home Link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.home_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    home_link: prismicT.LinkField;
    /**
     * Home Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.home_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    home_link_text: prismicT.KeyTextField;
    /**
     * About Link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.about_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    about_link: prismicT.LinkField;
    /**
     * About Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.about_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_link_text: prismicT.KeyTextField;
    /**
     * Service link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.service_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    service_link: prismicT.LinkField;
    /**
     * service text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.service_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    service_text: prismicT.KeyTextField;
    /**
     * Specialists Link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.specialists_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    specialists_link: prismicT.LinkField;
    /**
     * Specialists Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.specialists_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    specialists_link_text: prismicT.KeyTextField;
    /**
     * Contact link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.contact_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    contact_link: prismicT.LinkField;
    /**
     * Contact Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.contact_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    contact_link_text: prismicT.KeyTextField;
    /**
     * phone link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.phone_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    phone_link: prismicT.LinkField;
    /**
     * phone number text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.phone_number_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone_number_text: prismicT.KeyTextField;
    /**
     * book appointment link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.book_appointment_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    book_appointment_link: prismicT.LinkField;
    /**
     * book appointment text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.book_appointment_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    book_appointment_text: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice = never;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;
export type AllDocumentTypes = BookAppointmentDocument | CompanyInfoDocument | ContactElementsDocument | DentistsDocument | FooterDocument | HomepageDocument | NavigationDocument;
/**
 * Primary content in Dentist → Primary
 *
 */
interface DentistSliceDefaultPrimary {
    /**
     * name field in *Dentist → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: dentist.primary.name
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
    /**
     * education field in *Dentist → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: dentist.primary.education
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    education: prismicT.TitleField;
    /**
     * profile image field in *Dentist → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: dentist.primary.profile_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    profile_image: prismicT.ImageField<never>;
}
/**
 * Default variation for Dentist Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Dentist`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DentistSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<DentistSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Dentist*
 *
 */
type DentistSliceVariation = DentistSliceDefault;
/**
 * Dentist Shared Slice
 *
 * - **API ID**: `dentist`
 * - **Description**: `Dentist`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DentistSlice = prismicT.SharedSlice<"dentist", DentistSliceVariation>;
/**
 * Primary content in Inputs → Primary
 *
 */
interface InputsSliceDefaultPrimary {
    /**
     * input button link field in *Inputs → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: inputs.primary.input_button_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    input_button_link: prismicT.LinkField;
    /**
     * input button text field in *Inputs → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: inputs.primary.input_button_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    input_button_text: prismicT.KeyTextField;
    /**
     * input big field in *Inputs → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: inputs.primary.input_big
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    input_big: prismicT.KeyTextField;
    /**
     * input big headline field in *Inputs → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: inputs.primary.input_big_headline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    input_big_headline: prismicT.RichTextField;
    /**
     * input big placeholder field in *Inputs → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: inputs.primary.input_big_placeholder
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    input_big_placeholder: prismicT.KeyTextField;
}
/**
 * Item in Inputs → Items
 *
 */
export interface InputsSliceDefaultItem {
    /**
     * input small field in *Inputs → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: inputs.items[].input_small
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    input_small: prismicT.KeyTextField;
}
/**
 * Default variation for Inputs Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Inputs`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InputsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<InputsSliceDefaultPrimary>, Simplify<InputsSliceDefaultItem>>;
/**
 * Slice variation for *Inputs*
 *
 */
type InputsSliceVariation = InputsSliceDefault;
/**
 * Inputs Shared Slice
 *
 * - **API ID**: `inputs`
 * - **Description**: `Inputs`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InputsSlice = prismicT.SharedSlice<"inputs", InputsSliceVariation>;
/**
 * Primary content in TextWithList → Primary
 *
 */
interface TextSliceDefaultPrimary {
    /**
     * paragraph field in *TextWithList → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: text.primary.paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
}
/**
 * Item in TextWithList → Items
 *
 */
export interface TextSliceDefaultItem {
    /**
     * list field in *TextWithList → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text.items[].list
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    list: prismicT.KeyTextField;
}
/**
 * Default variation for TextWithList Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextSliceDefaultPrimary>, Simplify<TextSliceDefaultItem>>;
/**
 * Slice variation for *TextWithList*
 *
 */
type TextSliceVariation = TextSliceDefault;
/**
 * TextWithList Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSlice = prismicT.SharedSlice<"text", TextSliceVariation>;
/**
 * Primary content in TextWithSlidingImages → Primary
 *
 */
interface TextWithSlidingImagesSliceDefaultPrimary {
    /**
     * Title field in *TextWithSlidingImages → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: text_with_sliding_images.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * paragraph field in *TextWithSlidingImages → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_with_sliding_images.primary.paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
}
/**
 * Item in TextWithSlidingImages → Items
 *
 */
export interface TextWithSlidingImagesSliceDefaultItem {
    /**
     * slideImage field in *TextWithSlidingImages → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: text_with_sliding_images.items[].slideImage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    slideImage: prismicT.ImageField<never>;
}
/**
 * Default variation for TextWithSlidingImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextWithSlidingImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextWithSlidingImagesSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextWithSlidingImagesSliceDefaultPrimary>, Simplify<TextWithSlidingImagesSliceDefaultItem>>;
/**
 * Slice variation for *TextWithSlidingImages*
 *
 */
type TextWithSlidingImagesSliceVariation = TextWithSlidingImagesSliceDefault;
/**
 * TextWithSlidingImages Shared Slice
 *
 * - **API ID**: `text_with_sliding_images`
 * - **Description**: `TextWithSlidingImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextWithSlidingImagesSlice = prismicT.SharedSlice<"text_with_sliding_images", TextWithSlidingImagesSliceVariation>;
/**
 * Primary content in TextWithTitle → Primary
 *
 */
interface TextWithTitleSliceDefaultPrimary {
    /**
     * Title field in *TextWithTitle → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: text_with_title.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * paragraph field in *TextWithTitle → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_with_title.primary.paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
}
/**
 * Default variation for TextWithTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextWithTitle`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextWithTitleSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextWithTitleSliceDefaultPrimary>, never>;
/**
 * Slice variation for *TextWithTitle*
 *
 */
type TextWithTitleSliceVariation = TextWithTitleSliceDefault;
/**
 * TextWithTitle Shared Slice
 *
 * - **API ID**: `text_with_title`
 * - **Description**: `TextWithTitle`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextWithTitleSlice = prismicT.SharedSlice<"text_with_title", TextWithTitleSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { BookAppointmentDocumentData, BookAppointmentDocumentDataSlicesSlice, BookAppointmentDocument, CompanyInfoDocumentData, CompanyInfoDocumentDataSlicesSlice, CompanyInfoDocument, ContactElementsDocumentData, ContactElementsDocument, DentistsDocumentData, DentistsDocumentDataSlicesSlice, DentistsDocument, FooterDocumentData, FooterDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, NavigationDocumentData, NavigationDocumentDataSlicesSlice, NavigationDocument, AllDocumentTypes, DentistSliceDefaultPrimary, DentistSliceDefault, DentistSliceVariation, DentistSlice, InputsSliceDefaultPrimary, InputsSliceDefaultItem, InputsSliceDefault, InputsSliceVariation, InputsSlice, TextSliceDefaultPrimary, TextSliceDefaultItem, TextSliceDefault, TextSliceVariation, TextSlice, TextWithSlidingImagesSliceDefaultPrimary, TextWithSlidingImagesSliceDefaultItem, TextWithSlidingImagesSliceDefault, TextWithSlidingImagesSliceVariation, TextWithSlidingImagesSlice, TextWithTitleSliceDefaultPrimary, TextWithTitleSliceDefault, TextWithTitleSliceVariation, TextWithTitleSlice };
    }
}
