// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Company info documents */
interface CompanyInfoDocumentData {
    /**
     * title field in *Company info*
     *
     * - **Field Type**: Title
     * - **Placeholder**: title of component
     * - **API ID Path**: company_info.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * paragraph field in *Company info*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: component paragraph
     * - **API ID Path**: company_info.paragraph
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
    /**
     * image field in *Company info*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Company info*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<CompanyInfoDocumentDataSlicesSlice>;
}
/**
 * Slice for *Company info → Slice Zone*
 *
 */
type CompanyInfoDocumentDataSlicesSlice = never;
/**
 * Company info document from Prismic
 *
 * - **API ID**: `company_info`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompanyInfoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<CompanyInfoDocumentData>, "company_info", Lang>;
/** Content for homepage documents */
interface HomepageDocumentData {
    /**
     * title field in *homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * company slogan field in *homepage*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.company_slogan
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    company_slogan: prismicT.TitleField;
    /**
     * cover photo mobile field in *homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.cover_photo_mobile
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_photo_mobile: prismicT.ImageField<never>;
    /**
     * cover photo tablet field in *homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.cover_photo_tablet
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_photo_tablet: prismicT.ImageField<never>;
    /**
     * cover photo desktop field in *homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.cover_photo_desktop
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover_photo_desktop: prismicT.ImageField<never>;
    /**
     * about company link field in *homepage*
     *
     * - **Field Type**: Link
     * - **Placeholder**: link to about page
     * - **API ID Path**: homepage.about_company_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    about_company_link: prismicT.LinkField;
    /**
     * about link text field in *homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.about_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_link_text: prismicT.KeyTextField;
    /**
     * book appointment link field in *homepage*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.book_appointment_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    book_appointment_link: prismicT.LinkField;
    /**
     * book appointment text field in *homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.book_appointment_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    book_appointment_text: prismicT.KeyTextField;
    /**
     * Slice Zone field in *homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = LandingPageSlice | CompanyInfoSlice;
/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
    /**
     * logo field in *Navigation*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * logo text field in *Navigation*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.logo_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    logo_text: prismicT.TitleField;
    /**
     * logo subtext field in *Navigation*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.logo_subtext
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    logo_subtext: prismicT.RichTextField;
    /**
     * Home Link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.home_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    home_link: prismicT.LinkField;
    /**
     * Home Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.home_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    home_link_text: prismicT.KeyTextField;
    /**
     * About Link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.about_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    about_link: prismicT.LinkField;
    /**
     * About Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.about_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    about_link_text: prismicT.KeyTextField;
    /**
     * Service link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.service_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    service_link: prismicT.LinkField;
    /**
     * service text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.service_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    service_text: prismicT.KeyTextField;
    /**
     * Specialists Link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.specialists_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    specialists_link: prismicT.LinkField;
    /**
     * Specialists Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.specialists_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    specialists_link_text: prismicT.KeyTextField;
    /**
     * Contact link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.contact_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    contact_link: prismicT.LinkField;
    /**
     * Contact Link Text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.contact_link_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    contact_link_text: prismicT.KeyTextField;
    /**
     * phone link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.phone_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    phone_link: prismicT.LinkField;
    /**
     * phone number text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.phone_number_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone_number_text: prismicT.KeyTextField;
    /**
     * book appointment link field in *Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.book_appointment_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    book_appointment_link: prismicT.LinkField;
    /**
     * book appointment text field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.book_appointment_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    book_appointment_text: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice = never;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;
export type AllDocumentTypes = CompanyInfoDocument | HomepageDocument | NavigationDocument;
/**
 * Primary content in CompanyInfo → Primary
 *
 */
interface CompanyInfoSliceDefaultPrimary {
    /**
     * Title field in *CompanyInfo → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: company_info.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *CompanyInfo → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: company_info.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * read more field in *CompanyInfo → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.primary.read_more
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    read_more: prismicT.LinkField;
    /**
     * read more text field in *CompanyInfo → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.primary.read_more_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    read_more_text: prismicT.KeyTextField;
    /**
     * image field in *CompanyInfo → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: company_info.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for CompanyInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CompanyInfo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CompanyInfoSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CompanyInfoSliceDefaultPrimary>, never>;
/**
 * Slice variation for *CompanyInfo*
 *
 */
type CompanyInfoSliceVariation = CompanyInfoSliceDefault;
/**
 * CompanyInfo Shared Slice
 *
 * - **API ID**: `company_info`
 * - **Description**: `CompanyInfo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CompanyInfoSlice = prismicT.SharedSlice<"company_info", CompanyInfoSliceVariation>;
/**
 * Primary content in LandingPage → Primary
 *
 */
interface LandingPageSliceDefaultPrimary {
    /**
     * Description field in *LandingPage → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: landing_page.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * more link field in *LandingPage → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.more_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    more_link: prismicT.LinkField;
    /**
     * more text field in *LandingPage → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.more_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    more_text: prismicT.KeyTextField;
    /**
     * book appointment link field in *LandingPage → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.book_appointment_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    book_appointment_link: prismicT.LinkField;
    /**
     * book appointment text field in *LandingPage → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.book_appointment_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    book_appointment_text: prismicT.KeyTextField;
    /**
     * background image desktop field in *LandingPage → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.background_image_desktop
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image_desktop: prismicT.ImageField<never>;
    /**
     * background image tablet field in *LandingPage → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.background_image_tablet
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image_tablet: prismicT.ImageField<never>;
    /**
     * background image mobile field in *LandingPage → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.background_image_mobile
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image_mobile: prismicT.ImageField<never>;
    /**
     * welcome text field in *LandingPage → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: landing_page.primary.welcome_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    welcome_text: prismicT.RichTextField;
}
/**
 * Default variation for LandingPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: `LandingPage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LandingPageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<LandingPageSliceDefaultPrimary>, never>;
/**
 * Slice variation for *LandingPage*
 *
 */
type LandingPageSliceVariation = LandingPageSliceDefault;
/**
 * LandingPage Shared Slice
 *
 * - **API ID**: `landing_page`
 * - **Description**: `LandingPage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LandingPageSlice = prismicT.SharedSlice<"landing_page", LandingPageSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CompanyInfoDocumentData, CompanyInfoDocumentDataSlicesSlice, CompanyInfoDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, NavigationDocumentData, NavigationDocumentDataSlicesSlice, NavigationDocument, AllDocumentTypes, CompanyInfoSliceDefaultPrimary, CompanyInfoSliceDefault, CompanyInfoSliceVariation, CompanyInfoSlice, LandingPageSliceDefaultPrimary, LandingPageSliceDefault, LandingPageSliceVariation, LandingPageSlice };
    }
}
