// Code generated by Slice Machine. DO NOT EDIT.

import CompanyInfo from './CompanyInfo';
import LandingPage from './LandingPage';

export {
	CompanyInfo,
	LandingPage,
};

export const components = {
	company_info: CompanyInfo,
	landing_page: LandingPage,
};
