// Code generated by Slice Machine. DO NOT EDIT.

import Dentist from './Dentist';
import Inputs from './Inputs';
import NavElements from './NavElements';
import TextWithList from './TextWithList';
import TextWithSlidingImages from './TextWithSlidingImages';
import TextWithTitle from './TextWithTitle';

export {
	Dentist,
	Inputs,
	NavElements,
	TextWithList,
	TextWithSlidingImages,
	TextWithTitle,
};

export const components = {
	dentist: Dentist,
	inputs: Inputs,
	nav_elements: NavElements,
	text: TextWithList,
	text_with_sliding_images: TextWithSlidingImages,
	text_with_title: TextWithTitle,
};
